services:
  - type: web
    name: nguvu-fit-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && flask db upgrade && python seed.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nguvu-fit-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGIN
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MPESA_ENV
        value: sandbox
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: FLASK_APP
        value: app.py

databases:
  - name: nguvu-fit-db
    plan: free
